/**
 * User-facing copy — single source of truth for product labels.
 * Change a value here instead of hunting strings across screens.
 */
import type { Modality } from '@/types/api';

export const BADGE_LABELS = {
  verified: 'Verificado',
  pending: 'Pendiente',
  availableNow: 'Disponible ahora',
  full: 'Lleno',
} as const;

export const DROPDOWN_LABELS = {
  myProfile: 'Mi Perfil',
  settings: 'Configuración',
  logOut: 'Cerrar Sesión',
} as const;

export const CLASS_CARD_LABELS = {
  spotsLeft: (count: number) => `${count} lugares disponibles`,
} as const;

export const CLASS_FORMAT_LABELS = {
  group: 'Grupal',
  individual: 'Privada',
} as const;

export function classFormatBadgeLabel(classFormat?: string): string {
  if (classFormat === 'individual') return CLASS_FORMAT_LABELS.individual;
  return CLASS_FORMAT_LABELS.group;
}

export const MODALITY_LABELS = {
  online: 'Online',
  inPerson: 'Presencial',
} as const;

export function modalityBadgeLabel(modality: Modality): string {
  return modality === 'online' ? MODALITY_LABELS.online : MODALITY_LABELS.inPerson;
}

export function modalityLocationLabel(modality: Modality, locationLabel?: string): string {
  if (modality === 'online') return MODALITY_LABELS.online;
  return locationLabel ?? MODALITY_LABELS.inPerson;
}

export const TAB_LABELS = {
  athlete: {
    home: 'Inicio',
    search: 'Buscar',
    bookings: 'Reservas',
    profile: 'Perfil',
  },
  instructor: {
    dashboard: 'Panel',
    classes: 'Clases',
    calendar: 'Calendario',
    earnings: 'Ingresos',
    jobs: 'Empleos',
    analytics: 'Analíticas',
    profile: 'Perfil',
  },
  gym: {
    dashboard: 'Panel',
    staff: 'Personal',
    members: 'Socios',
    membershipPlans: 'Planes',
    jobs: 'Empleos',
    classes: 'Clases',
    earnings: 'Ingresos',
    analytics: 'Analíticas',
    profile: 'Gimnasio',
  },
} as const;

export const PROFILE_PAGE_LABELS = {
  title: 'Mi perfil',
  memberSince: 'Miembro desde',
  editProfile: 'Editar perfil',
  cancelEdit: 'Cancelar',
  quickLinks: 'Accesos rápidos',
  accountSecurity: 'Seguridad de la cuenta',
  notificationsTitle: 'Notificaciones',
  notificationsSubtitle: 'Gestiona tus preferencias de alertas y recordatorios',
  saved: 'Perfil actualizado correctamente',
  savingProfile: 'Guardando perfil…',
  passwordChangeViaEmail: 'Para cambiar tu contraseña, usa el enlace que te enviamos por correo.',
  resetPasswordLink: 'Restablecer contraseña por correo',
  favoriteSports: 'Deportes favoritos',
  trainingLevel: 'Nivel de entrenamiento',
  trainingLevelHint: 'Se usa como preferencia al buscar clases.',
  certifications: 'Certificaciones',
  photoGallery: 'Galería de fotos',
  availableNow: 'Disponible ahora',
  notAvailable: 'No disponible',
  hourlyRate: 'Tarifa por hora (UYU)',
  hourlyRateUnset: 'Sin tarifa definida',
  bio: 'Biografía',
  bioUnset: 'Sin biografía',
  deleteAccountTitle: 'Eliminar cuenta',
  deleteAccountWarning:
    'Esta acción es permanente. Se eliminarán tus datos, reservas y contenido asociado a tu perfil.',
  deleteAccountConfirmPrompt: 'Escribe tu correo para confirmar',
  deleteAccountButton: 'Eliminar mi cuenta',
  deleteAccountSuccess: 'Tu cuenta fue eliminada correctamente.',
} as const;

export const VERIFICATION_LABELS = {
  bannerUnverified:
    'Verificá tu perfil para generar más confianza y aparecer mejor posicionado.',
  bannerPending: 'Tu solicitud de verificación está en revisión. Te avisaremos por correo.',
  bannerRejected: 'Tu verificación fue rechazada. Podés volver a intentarlo.',
  bannerVerified: 'Tu perfil está verificado con la insignia Fitnexia.',
  ctaStart: 'Verificar perfil',
  ctaRetry: 'Reintentar verificación',
  statusInReview: 'En revisión',
  pageTitle: 'Verificación de perfil',
  pageIntro:
    'Subí los documentos requeridos. No se publicarán en tu perfil; solo el equipo Fitnexia los revisará.',
  docDniFront: 'DNI — frente',
  docDniBack: 'DNI — dorso',
  docCertification: 'Título o certificación profesional',
  docPhotoHint: 'Solo fotos (JPEG, PNG o WebP) · máx. 10 MB',
  docCertHint: 'Foto o PDF (JPEG, PNG, WebP, PDF) · máx. 10 MB',
  docInvalidPhoto: 'El DNI debe subirse como foto (JPEG, PNG o WebP).',
  docInvalidCert: 'La certificación debe ser una foto (JPEG, PNG o WebP) o un PDF.',
  submitting: 'Enviando solicitud…',
  submit: 'Enviar solicitud',
  submitSuccessTitle: 'Solicitud enviada',
  submitSuccessBody:
    'Recibimos tu solicitud. Te avisaremos por correo cuando la revisión esté lista.',
  pendingReadOnly: 'Ya tenés una solicitud en revisión. No podés enviar otra hasta que respondamos.',
  alreadyVerified: 'Tu perfil ya está verificado.',
  rejectionReason: 'Motivo del rechazo',
  publishWarning:
    'Tu perfil aún no está verificado. Podés publicar, pero los atletas verán que no tenés la insignia Fitnexia.',
  searchVerifiedOnly: 'Solo verificados',
} as const;

/** F-11 — advanced search filters */
export const ADVANCED_SEARCH_LABELS = {
  sectionTitle: 'Búsqueda avanzada',
  toggleShow: 'Mostrar filtros avanzados',
  toggleHide: 'Ocultar filtros avanzados',
  level: 'Nivel',
  language: 'Idioma de la clase',
  instructorGender: 'Género del instructor',
  anyLevel: 'Cualquier nivel',
  anyLanguage: 'Cualquier idioma',
  anyGender: 'Cualquier género',
  emptyHint:
    'No hay clases que coincidan con los filtros avanzados. Probá quitar alguno o ampliar la búsqueda.',
  levelTag: (label: string) => `Nivel: ${label}`,
  languageTag: (label: string) => `Idioma: ${label}`,
  genderTag: (label: string) => `Instructor: ${label}`,
} as const;

export const PAYOUT_ACCOUNT_LABELS = {
  title: 'Cuenta de cobros',
  intro:
    'Conectá tu cuenta de Mercado Pago para recibir el neto de tus clases automáticamente cuando el marketplace esté activo.',
  provider: 'Mercado Pago',
  statusLabel: 'Estado',
  statusConnected: 'Conectada',
  statusDisconnected: 'No conectada',
  statusRevoked: 'Desvinculada',
  collectorLabel: 'Cuenta MP',
  connectedAtLabel: 'Conectada el',
  connectedBenefit:
    'Los pagos de tus clases se acreditan directo en tu cuenta de Mercado Pago, con la comisión Fitnexia descontada automáticamente.',
  marketplacePending: 'Marketplace en configuración — tu cliente debe entregar credenciales MP.',
  connect: 'Conectar Mercado Pago',
  reconnect: 'Volver a conectar',
  disconnect: 'Desvincular cuenta',
  refresh: 'Actualizar estado',
  waitingAuth:
    'Completá la autorización en la pestaña de Mercado Pago. Verificamos la conexión automáticamente…',
  connectedNoticeTitle: 'Cuenta conectada',
  connectedNoticeMessage:
    'Tu cuenta de Mercado Pago quedó vinculada. Vas a recibir el neto de tus cobros automáticamente.',
  disconnectedNoticeTitle: 'Cuenta desvinculada',
  disconnectedNoticeMessage:
    'Tu cuenta de Mercado Pago fue desvinculada. Podés volver a conectarla cuando quieras.',
  connectNoticeTitle: 'Marketplace en configuración',
  connectNoticeMessage:
    'El marketplace aún está en configuración. Tu cliente debe entregar las credenciales de Mercado Pago para habilitar la conexión de cuentas de cobro.',
  loadError: 'No se pudo cargar el estado de la cuenta de cobros.',
  connectError: 'No se pudo iniciar la conexión con Mercado Pago.',
  disconnectError: 'No se pudo desvincular la cuenta.',
} as const;

export const INSTRUCTOR_PLAN_LABELS = {
  choosePlan: 'Cambiar a este plan',
  pendingBadge: 'Pago pendiente',
  completePayment: 'Completar pago en Mercado Pago',
  checkoutOpenedTitle: 'Autorización en Mercado Pago',
  checkoutOpenedBody:
    'Abrimos Mercado Pago en una pestaña nueva. Cuando completes la autorización, tu plan se activa automáticamente.',
  waitingActivation: 'Esperando confirmación del pago…',
  activationTimeout:
    'Todavía no recibimos la confirmación del pago. Si ya pagaste, actualizá esta página en unos minutos.',
  subscribeSuccess: 'Plan actualizado correctamente.',
  subscribeError: 'No se pudo iniciar la suscripción.',
} as const;

export const PROFILE_MENU_LABELS = {
  favoriteSports: 'Deportes favoritos',
  notifications: 'Notificaciones',
  paymentMethods: 'Métodos de pago',
  payoutAccount: 'Cuenta de cobros',
  planCommission: 'Plan y comisión',
  helpSupport: 'Ayuda y soporte',
  location: 'Ubicación',
  disciplines: 'Disciplinas',
  certifications: 'Certificaciones',
  scheduleAvailability: 'Horario y disponibilidad',
  photoGallery: 'Galería de fotos',
  instructors: 'Instructores',
} as const;

export const SCREEN_TITLES = {
  profile: 'Perfil',
  gymProfile: 'Perfil del gimnasio',
  editProfile: 'Editar perfil',
  notifications: 'Notificaciones',
  favoriteSports: 'Deportes favoritos',
  paymentMethods: 'Métodos de pago',
  payoutAccount: 'Cuenta de cobros',
  helpSupport: 'Ayuda y soporte',
  planCommission: 'Plan y comisión',
  inviteInstructor: 'Invitar instructor',
  class: 'Clase',
  classDetails: 'Detalles de la clase',
  classNotFound: 'Clase no encontrada',
  paymentHistory: 'Historial de pagos',
  clubMembership: 'Membresía del club',
  clubMembershipStatement: 'Estado de cuenta',
  memberInvites: 'Invitaciones de socios',
  recordedLibrary: 'Clases grabadas',
  analytics: 'Analíticas',
} as const;

export const BUTTON_LABELS = {
  signOut: 'Cerrar sesión',
  save: 'Guardar',
  saveChanges: 'Guardar cambios',
  edit: 'Editar',
  continue: 'Continuar',
  createAccount: 'Crear cuenta',
  signIn: 'Iniciar sesión',
  bookNow: 'Reservar ahora',
  joinWaitlist: 'Unirse a la lista de espera',
  joinWaitlistShort: 'Unirse a lista de espera',
  classFull: 'Clase llena',
  viewProfile: 'Perfil',
  confirmBooking: 'Confirmar reserva',
  payAndConfirm: 'Pagar y confirmar',
  completePayment: 'Completar pago',
  manageBooking: 'Gestionar reserva',
  cancelClass: 'Cancelar clase',
  removeFromStaff: 'Quitar del equipo',
  cancelInvite: 'Cancelar solicitud',
} as const;

export const CLASS_DETAIL_LABELS = {
  when: 'Cuándo',
  duration: 'Duración',
  where: 'Dónde',
  price: 'Precio',
  spots: 'Lugares',
  about: 'Acerca de',
  hostedBy: 'Organiza',
  description: 'Descripción',
  level: 'Nivel',
  language: 'Idioma',
  instructorGender: 'Género del instructor',
  locationTbd: 'Por confirmar',
  full: 'Lleno',
  fullWaitlist: 'Lleno — lista de espera disponible',
  liveStream: 'Transmisión en vivo en Fitnexia',
  onlineSessionLink: 'Sesión online (enlace compartido después de reservar)',
  cancellationPolicy: (hours: number) =>
    `Reembolso completo si cancelás con al menos ${hours} h de anticipación.`,
} as const;

export function classSpotsLabel(
  spotsLeft: number,
  capacity: number,
  options?: { waitlistEnabled?: boolean },
): string {
  if (spotsLeft === 0) {
    return options?.waitlistEnabled
      ? CLASS_DETAIL_LABELS.fullWaitlist
      : CLASS_DETAIL_LABELS.full;
  }
  return `${spotsLeft} de ${capacity} disponibles`;
}

export const AUTH_LABELS = {
  welcomeBack: 'Bienvenido de nuevo',
  signInSubtitle: 'Inicia sesión para continuar',
  chooseProfile: 'Elige tu perfil',
  createAccount: 'Crear cuenta',
  howWillYouUse: '¿Cómo usarás Fitnexia?',
  completeProfile: 'Completa tu perfil básico',
  gymSchoolName: 'Nombre del gimnasio / escuela',
  gymSchoolPlaceholder: 'Nombre de tu instalación',
  firstName: 'Nombre',
  lastName: 'Apellidos',
  email: 'Correo electrónico',
  password: 'Contraseña',
  logoPhoto: 'Logo / foto',
  profilePhoto: 'Foto de perfil',
  acceptTermsPrefix: 'He leído y acepto los',
  termsAndConditions: 'Términos y condiciones',
  acceptTermsMiddle: 'y la',
  privacyPolicy: 'Política de privacidad',
} as const;

export const LEGAL_LABELS = {
  tableOfContents: 'Contenido',
  lastUpdated: 'Última actualización',
  relatedDocuments: 'Documentos relacionados',
  termsLink: 'Términos y condiciones',
  privacyLink: 'Política de privacidad',
  backToHome: 'Volver al inicio',
} as const;

export const ALERT_LABELS = {
  signOutTitle: 'Cerrar sesión',
  signOutMessage: '¿Estás seguro?',
  cancel: 'Cancelar',
  missingInfoTitle: 'Información faltante',
  fillAllFields: 'Por favor, completa todos los campos.',
  gymNameRequired: 'El nombre del gimnasio / escuela es obligatorio.',
  acceptTermsRequired: 'Debes aceptar los términos y condiciones y la política de privacidad.',
  savedTitle: 'Guardado',
} as const;

export const GENERAL_LABELS = {
  back: 'Volver',
  photoGallery: 'Galería de fotos',
  favoriteSports: 'Deportes favoritos',
  disciplines: 'Disciplinas',
  alreadyHaveAccount: '¿Ya tienes una cuenta?',
  forgotPassword: '¿Olvidaste tu contraseña?',
  google: 'Google',
  continueWith: 'Continuar con',
  orContinueWith: 'o continúa con correo',
  quickDemo: 'Demo rápida (simulada)',
  coach: 'Entrenador',
  newHere: '¿Eres nuevo aquí?',
  resetPassword: 'Restablecer contraseña',
  checkYourEmail: 'Revisa tu correo electrónico',
  ifAccountExists: 'Si existe una cuenta para',
  willReceiveResetInstructions: 'recibirás instrucciones para restablecer (simulada).',
  enterYourEmail: 'Ingresa tu correo electrónico y te enviaremos un enlace de restablecimiento.',
  sendResetLink: 'Enviar enlace de restablecimiento',
  backToSignIn: 'Volver a iniciar sesión',
  somethingWentWrong: '¡Algo salió mal!',
  weAreSorryError: 'Lo sentimos, pero hubo un error al cargar esta página.',
  tryAgain: 'Intentar de nuevo',
  goBackHome: 'Volver al inicio',
  pageDoesNotExist: '¡Ups! La página que buscas no existe.',
  search: 'Buscar',
  classInstructorGym: 'Clase, instructor o gimnasio...',
  cityNeighborhoodVenue: 'Ciudad, barrio o lugar...',
  discipline: 'Disciplina',
  modality: 'Modalidad',
  schedule: 'Horario',
  price: 'Precio',
  clearFilters: 'Limpiar filtros',
  class: 'clase',
  classes: 'clases',
  goodMorning: '¡Buenos días!',
  findYourNextClass: 'Encuentra tu próxima clase',
  searchClassesCoachesGyms: 'Buscar clases, entrenadores, gimnasios...',
  nearby: 'Cerca',
  recommendedForYou: 'Recomendado para ti',
  nearbyPopularHome: 'Cercanas y populares',
  athleteHomeViewByType: 'Por tipo',
  athleteHomeViewByFeed: 'Por feed',
  athleteHomeViewLabel: 'Vista del inicio',
  athleteHomeViewHint: 'Elegí cómo explorar las clases de tu feed',
  athleteHomeViewByTypeDesc: 'Regulares y puntuales',
  athleteHomeViewByFeedDesc: 'Recomendadas y cercanas',
  athleteHomeFeedEyebrow: 'Modo feed',
  athleteHomeClassCount: (n: number) => `${n} ${n === 1 ? 'clase' : 'clases'}`,
  /** Athlete home — recurring vs one-off (F-13) */
  generalClasses: 'Clases generales',
  regularClassesHome: 'Clases regulares',
  athleteHomeHeroBody:
    'Descubrí clases regulares y puntuales cerca tuyo. Reservá en segundos con instructores y centros verificados.',
  athleteHomeSearchCta: 'Explorar clases',
  athleteHomeBrandChip: 'Fitnexia · clases, coaches y gimnasios',
  regularClassesSubtitle: 'Series semanales para entrenar con constancia',
  generalClassesSubtitle: 'Sesiones puntuales listas para reservar ahora',
  regularClassesEmpty:
    'Todavía no hay clases regulares disponibles. Explorá el buscador para encontrar una.',
  generalClassesEmpty:
    'Todavía no hay clases generales en tu feed. Probá otra búsqueda o volvé más tarde.',
  recommendedClassesSubtitle: 'Seleccionadas según tu actividad y preferencias',
  nearbyPopularSubtitle: 'Clases con buena demanda cerca de vos',
  recommendedClassesEmpty:
    'Todavía no hay recomendaciones en tu feed. Explorá el buscador para descubrir clases.',
  nearbyPopularEmpty:
    'Todavía no hay clases cercanas o populares. Probá otra búsqueda o volvé más tarde.',
  athleteSearchEyebrow: 'Descubrí',
  athleteSearchSubtitle:
    'Filtrá por disciplina, modalidad, horario y precio para encontrar tu próxima clase.',
  athleteSearchResults: 'Resultados',
  athleteSearchBarEyebrow: 'Explorar Fitnexia',
  athleteSearchBarHint: 'Escribí y filtrá al instante',
  athleteSearchQueryLabel: 'Qué buscás',
  athleteSearchLocationLabel: 'Dónde',
  athleteBookingsEyebrow: 'Tu agenda',
  athleteBookingsSubtitle:
    'Consultá reservas próximas e historial, y gestioná pagos o cancelaciones.',
  athleteProfileEyebrow: 'Tu cuenta',
  athleteProfileSubtitle: 'Datos, preferencias y accesos rápidos de tu cuenta Fitnexia.',
  athleteNotificationsEyebrow: 'Inbox',
  athleteNotificationsSubtitle: 'Confirmaciones, recordatorios y novedades de Fitnexia.',
  athletePaymentsEyebrow: 'Pagos',
  athletePaymentsSubtitle: 'Historial de cargos y reembolsos de tus reservas.',
  athleteSupportEyebrow: 'Ayuda',
  athleteSupportSubtitle: 'Escribinos y seguí el estado de tus consultas.',
  reviews: 'Reseñas',
  min: 'min',
  loading: 'Cargando…',
  preparingAccount: 'Preparando tu cuenta…',
  loadingYourData: 'Cargando tu contenido…',
  book: 'Reservar',
  total: 'Total',
  paymentIntegrationDemo: 'Demo de integración de pago: Simularemos un checkout de Mercado Pago.',
  choosePaymentModel: 'Elegí cómo querés pagar',
  paymentModelPerClass: 'Pago por clase',
  paymentModelMonthlyUnlimited: 'Plan mensual ilimitado',
  paymentModelPerPeriod: 'Pago por período',
  billingPeriodWeekly: 'Semanal',
  billingPeriodMonthly: 'Mensual',
  billingPeriodQuarterly: 'Trimestral',
  subscriptionCoversBooking: 'Tu plan mensual cubre esta reserva. Confirmá sin cargo adicional.',
  secureCheckout: 'Checkout seguro',
  orderSummary: 'Resumen del pedido',
  classDetails: 'Detalles de la clase',
  waitlistNote: 'Te avisaremos si se libera un lugar en esta clase.',
  selectPaymentMethod: 'Seleccionar método de pago',
  mercadoPago: 'Mercado Pago',
  creditCard: 'Tarjeta de crédito',
  debitCard: 'Tarjeta de débito',
  joinedWaitlistTitle: '¡Te has unido a la lista de espera!',
  joinedWaitlistBody: 'Te has unido a la lista de espera para {classTitle}. Te notificaremos si se libera un lugar.',
  onWaitlistAlert: 'En lista de espera — te notificaremos cuando se libere un lugar.',
  bookingConfirmedTitle: '¡Reserva confirmada!',
  bookingConfirmedBody: 'Tu reserva para {classTitle} ha sido confirmada.',
  paymentSuccessfulAlert: '¡Pago exitoso! Revisa tus reservas.',
  myBookings: 'Mis reservas',
  hideCalendar: 'Ocultar calendario',
  showCalendar: 'Mostrar calendario',
  noBookingsForDay: 'No hay reservas para este día.',
  status: 'Estado',
  upcoming: 'Próximas',
  history: 'Historial',
  noBookingsInTab: 'No hay reservas en esta pestaña.',
  cancel: 'Cancelar',
  cancelBooking: '¿Cancelar reserva?',
  fullRefund: 'Recibirás un reembolso completo de {amount}.',
  lateCancellationNoRefund: (hours: number) =>
    `Si cancelás con menos de ${hours} h de anticipación, no hay reembolso.`,
  confirmCancel: 'Confirmar cancelación',
  keepBooking: 'Mantener reserva',
  bookingCancelledTitle: 'Reserva cancelada',
  bookingCancelledBody: 'Tu reserva para {classTitle} ha sido cancelada. Reembolso: {amount}',
  bookingCancelledAlert: '¡Reserva cancelada!',
  leaveReview: 'Dejar reseña',
  review: 'Reseña',
  bookingNotFound: 'Reserva no encontrada.',
  notFound: 'No encontrado.',
  leaveAReview: 'Dejar una reseña',
  rating: 'Calificación',
  shareYourExperience: 'Comparte tu experiencia...',
  submitReview: 'Enviar reseña',
  reviewSubmittedAlert: '¡Reseña enviada!',
  firstName: 'Nombre',
  lastName: 'Apellidos',
  email: 'Correo electrónico',
  none: 'Ninguno',
  paymentHistory: 'Historial de pagos',
  changePassword: 'Cambiar contraseña',
  currentPassword: 'Contraseña actual',
  newPassword: 'Nueva contraseña',
  confirmNewPassword: 'Confirmar nueva contraseña',
  newPasswordsDoNotMatch: 'Las nuevas contraseñas no coinciden',
  passwordChangedSuccessfully: '¡Contraseña cambiada exitosamente!',
  failedToChangePassword: 'Error al cambiar la contraseña',
  change: 'Cambiar',
  // cancel: 'Cancelar',
  saveChange: 'Guardar cambios',
  noPaymentHistoryYet: 'Aún no hay historial de pagos.',
  classBooking: 'Reserva de clase',
  paid: 'Pagado',
  refunded: 'Reembolsado',
} as const;

export const DISCIPLINE_LABELS = {
  Musculación: 'Musculación',
  'Entrenamiento Funcional': 'Entrenamiento Funcional',
  'Entrenamiento Personalizado': 'Entrenamiento Personalizado',
  'Entrenamiento para adultos mayores': 'Entrenamiento para adultos mayores',
  'Entrenamiento para embarazadas': 'Entrenamiento para embarazadas',
  'Zumba/Ritmos': 'Zumba/Ritmos',
  'Indoor Cycling': 'Ciclismo indoor',
  'Pilates Mat/Reformer': 'Pilates suelo/reformer',
  Tenis: 'Tenis',
  Pádel: 'Pádel',
  Hidrogimnasia: 'Hidrogimnasia',
  Natación: 'Natación',
  Fútbol: 'Fútbol',
  Basquetbol: 'Basquetbol',
  Voleibol: 'Voleibol',
  Hockey: 'Hockey',
  Yoga: 'Yoga',
  Crossfit: 'Entrenamiento cross',
  Otros: 'Otros',
  // Legacy values (display only — not selectable in dropdowns)
  CrossFit: 'Entrenamiento cross',
  Tennis: 'Tenis',
  Swimming: 'Natación',
  HIIT: 'HIIT',
  Pilates: 'Pilates suelo/reformer',
  Boxing: 'Boxeo',
  Running: 'Correr',
  Padel: 'Pádel',
  'Entrenamiento personal': 'Entrenamiento Personalizado',
  Fuerza: 'Musculación',
  Other: 'Otros',
  'Fitness Funcional': 'Entrenamiento Funcional',
} as const;

export const SCHEDULE_FILTER_LABELS = {
  'Any time': 'Cualquier horario',
  'Next 7 days': 'Próximos 7 días',
  'Next 30 days': 'Próximos 30 días',
  'Morning': 'Mañana',
  'Afternoon': 'Tarde',
  'Evening': 'Noche',
} as const;

export const PRICE_RANGE_LABELS = {
  'Any price': 'Cualquier precio',
  'Under 800 UYU': 'Menos de 800 UYU',
  '800 – 1.400 UYU': '800 – 1.400 UYU',
  'Over 1.400 UYU': 'Más de 1.400 UYU',
} as const;

export const ROLE_TITLES = {
  athlete: 'Atleta',
  instructor: 'Instructor',
  institution: 'Gimnasio / Escuela',
} as const;

export const ROLE_DESCRIPTIONS = {
  athlete: 'Encuentra y reserva clases cerca de ti',
  instructor: 'Enseña y gestiona tu horario',
  institution: 'Gestiona instructores y clases grupales',
} as const;

export const LANDING_LABELS = {
  badge: 'MVP · Uruguay',
  nav: {
    what: '¿Qué es?',
    howItWorks: 'Cómo funciona',
    whoIsItFor: 'Para quién es',
    benefits: 'Beneficios',
    start: 'Empezar',
  },
  whatEyebrow: '¿Qué es?',
  whatTitle: 'La plataforma que conecta profesionales del fitness, usuarios y gimnasios en un solo lugar.',
  whatBody:
    'Fitnexia es el ecosistema digital del fitness en Uruguay: descubre clases, reserva con instructores verificados y gestiona tu centro o tu marca personal desde una sola web.',
  trust: ['Instructores verificados', 'Reservas en minutos', 'Pagos transparentes'],
  whoEyebrow: 'Para quién es',
  whoTitle: '¿Para quién es Fitnexia?',
  whoSubtitle: 'Una plataforma pensada para los tres lados del fitness.',
  roles: {
    athlete: {
      label: 'Quiero entrenar',
      headline: 'Encuentra tu próxima rutina',
      body: 'Descubre clases cerca de ti, reserva con instructores verificados y explora nuevas disciplinas.',
      cta: 'Crear cuenta como atleta',
    },
    instructor: {
      label: 'Soy instructor',
      headline: 'Haz crecer tu marca personal',
      body: 'Publica tus clases, gestiona tu agenda y recibe solicitudes de gimnasios que buscan talento.',
      cta: 'Registrarme como instructor',
    },
    institution: {
      label: 'Tengo un gimnasio',
      headline: 'Coordina tu equipo sin fricción',
      body: 'Encuentra profesionales verificados, organiza clases grupales y administra tu centro en un solo panel.',
      cta: 'Registrar mi gimnasio',
    },
  },
  howEyebrow: 'Cómo funciona',
  howTitle: 'Cómo funciona',
  howSubtitle: 'Tres pasos para empezar a usar Fitnexia.',
  steps: [
    {
      num: '1',
      title: 'Crea tu perfil',
      body: 'Regístrate en minutos como atleta, instructor o gimnasio. Configura tu información y especialidades.',
    },
    {
      num: '2',
      title: 'Conecta con la comunidad',
      body: 'Los instructores publican clases, los gimnasios buscan talento y los usuarios encuentran su próxima sesión.',
    },
    {
      num: '3',
      title: 'Reserva, coordina y entrena',
      body: 'Reservas con confirmación inmediata, calendarios sincronizados y recordatorios para no perderte nada.',
    },
  ],
  benefitsEyebrow: 'Beneficios',
  benefitsTitle: 'Beneficios por perfil',
  benefitsSubtitle: 'Lo que cada uno gana con Fitnexia.',
  benefitsTabs: {
    athlete: 'Usuarios',
    instructor: 'Instructores',
    institution: 'Gimnasios',
  },
  benefits: {
    athlete: [
      {
        title: 'Clases cerca de ti',
        body: 'Busca por deporte, ubicación y modalidad con mapa integrado y filtros inteligentes.',
      },
      {
        title: 'Instructores verificados',
        body: 'Perfiles con reseñas, certificaciones y disponibilidad en tiempo real.',
      },
      {
        title: 'Reserva sin complicaciones',
        body: 'Confirma tu plaza en segundos, presencial u online, con historial de pagos.',
      },
    ],
    instructor: [
      {
        title: 'Publica tus clases',
        body: 'Sube tu agenda y empieza a recibir reservas en minutos.',
      },
      {
        title: 'Haz crecer tu marca',
        body: 'Perfil profesional con reseñas, certificaciones y portfolio visible.',
      },
      {
        title: 'Recibe solicitudes',
        body: 'Los gimnasios te encuentran y te contactan para sumarte a su grilla.',
      },
    ],
    institution: [
      {
        title: 'Talento verificado',
        body: 'Encuentra instructores con perfil completo y reseñas de la comunidad.',
      },
      {
        title: 'Gestión centralizada',
        body: 'Clases, staff y reservas en un panel diseñado para centros deportivos.',
      },
      {
        title: 'Más visibilidad',
        body: 'Tu gimnasio aparece en búsquedas locales y atrae nuevos socios.',
      },
    ],
  },
  launchBadge: 'Ya disponible · MVP',
  launchTitle: 'El fitness uruguayo, conectado',
  launchSubtitle: 'Explora la plataforma hoy mismo. Sin listas de espera — crea tu cuenta y empieza a entrenar.',
  stats: [
    { value: '150+', label: 'Usuarios activos' },
    { value: '50+', label: 'Clases publicadas' },
    { value: '4.8★', label: 'Valoración media' },
  ],
  ctaTitle: '¿Listo para tu próximo entrenamiento?',
  ctaSubtitle: 'Únete a Fitnexia y descubre clases, instructores y gimnasios en TODO Uruguay.',
  ctaButton: 'Crear cuenta gratis',
  ctaNote: '¿Ya tienes cuenta? Inicia sesión y continúa donde lo dejaste.',
} as const;

export const ONBOARDING_LABELS = {
  intro: 'El marketplace que conecta atletas, instructores y gimnasios en TODO Uruguay.',
  tagline: 'Tu próximo entrenamiento empieza aquí.',
  slides: [
    {
      title: 'Encuentra tu próxima clase',
      body: 'Descubre clases de deportes y fitness de los mejores instructores y gimnasios cerca de ti.',
    },
    {
      title: 'Reserva en un solo toque',
      body: 'Reserva sesiones presenciales u online. Recibe recordatorios antes de cada clase.',
    },
    {
      title: 'Entrena con los mejores',
      body: 'Instructores verificados, reseñas reales y un programa de fidelidad que te recompensa.',
    },
  ],
  next: 'Siguiente',
  getStarted: 'Empezar',
  skip: 'Omitir',
} as const;

export const NOTIFICATIONS_LABELS = {
  noNotificationsYet: 'Aún no hay notificaciones.',
  managePreferences: 'Preferencias de notificaciones',
  openInbox: 'Ver bandeja',
  markAllRead: 'Marcar todo como leído',
  unreadCount: (count: number) =>
    count === 1 ? '1 sin leer' : `${count} sin leer`,
  hubSubtitle: 'Alertas de reservas, pagos y actividad en la app',
  preferencesTitle: 'Preferencias de alertas',
  preferencesHint: 'Elegí qué avisos querés recibir por push y correo.',
  preferencesSaved: 'Preferencia actualizada',
  sectionBookings: 'Clases y reservas',
  sectionAccount: 'Cuenta y club',
  preferences: {
    bookingConfirmed: 'Reserva confirmada',
    classReminders: 'Recordatorios de clase',
    paymentUpdates: 'Actualizaciones de pago',
    creditsExpiring: 'Créditos a punto de vencer',
    membershipReminders: 'Recordatorios de cuota del club',
    memberDelinquencyAlerts: 'Alertas de socios morosos',
    marketing: 'Marketing y consejos',
  },
} as const;

/** Virtual V2/V3 UI copy (mock data until backend APIs ship). */
export const MOCK_V2V3_LABELS = {
  mockDataBadge: 'Datos de demostración',
  waitlistJoined: 'Te uniste a la lista de espera. Te avisaremos si se libera un cupo.',
  waitlistPosition: (position: number) => `Posición #${position} en la lista de espera`,
  waitlistEmpty: 'No estás en ninguna lista de espera.',
  leaveWaitlist: 'Salir de la lista',
  waitlistTitle: 'Lista de espera',
  waitlistSpotOffer: 'Hay un cupo disponible. Confirmá tu reserva antes de que expire.',
  waitlistConfirmSpot: 'Confirmar cupo',
  waitlistStatusWaiting: 'En espera',
  waitlistStatusOffered: 'Cupo disponible',
  creditsBalance: 'Créditos de fidelidad',
  creditsApply: 'Canjear 10 créditos por esta clase (gratis)',
  creditsApplied: 'Reserva confirmada con créditos de fidelidad',
  creditsHint: (balance: number, until: number) =>
    `${balance} créditos · ${until} más para una clase gratis`,
  creditsHistory: 'Historial de créditos',
  creditsEmptyHistory: 'Todavía no hay movimientos de créditos.',
  digitalWallets: 'Billeteras digitales',
  payWithApplePay: 'Apple Pay',
  payWithGooglePay: 'Google Pay',
  walletDemoNote: 'Pago simulado — no se procesará ningún cargo real.',
  displayCurrency: 'Moneda de visualización',
  displayCurrencyHint: 'Los precios se muestran en la moneda elegida (tipo de cambio simulado).',
  recordedLibrary: 'Biblioteca de clases grabadas',
  recordedLibraryHint: 'Sesiones bajo demanda disponibles para socios.',
  continueWatching: 'Continuar viendo',
  watchNow: 'Reproducir',
  reviewResponse: 'Respuesta del instructor',
  replyToReview: 'Responder reseña',
  replyPlaceholder: 'Escribe una respuesta pública…',
  replySaved: 'Respuesta publicada.',
  supportTitle: 'Ayuda y soporte',
  supportNewTicket: 'Nuevo ticket',
  supportSubject: 'Asunto',
  supportMessage: 'Mensaje',
  supportSubmit: 'Enviar ticket',
  supportTicketSent: 'Ticket enviado. Te responderemos a la brevedad.',
  supportStatus: {
    open: 'Abierto',
    in_progress: 'En progreso',
    resolved: 'Resuelto',
  },
  paymentMethodAdd: 'Agregar tarjeta',
  paymentMethodDefault: 'Predeterminada',
  paymentMethodRemove: 'Eliminar',
  paymentMethodDemo: 'Tarjetas de demostración — no se almacenan datos reales.',
  analyticsTitle: 'Analíticas',
  analyticsWeekly: 'Reservas por día',
  analyticsTopClasses: 'Clases con mejor ocupación',
  analyticsTopInstructors: 'Instructores con más ingresos',
  analyticsRetention: 'Retención',
  analyticsOccupancy: 'Ocupación',
  analyticsBookings: 'Reservas',
  analyticsRevenue: 'Ingresos',
  analyticsPeriodDay: 'Día',
  analyticsPeriodWeek: 'Semana',
  analyticsPeriodMonth: 'Mes',
  analyticsEmpty: 'Todavía no hay datos para este período.',
  analyticsLoadError: 'No se pudieron cargar las analíticas. Intentá de nuevo.',
  analyticsLoading: 'Cargando analíticas…',
  weeklyScheduleTitle: 'Horario semanal',
  weeklyScheduleSave: 'Guardar horario',
  weeklyScheduleSaved: 'Horario guardado (demostración).',
  weekdayNames: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  // Courts module
  courtsTitle: 'Canchas y espacios',
  courtsManage: 'Gestionar canchas',
  courtsBook: 'Reservar cancha',
  courtsMyBookings: 'Mis reservas de cancha',
  courtType: 'Tipo',
  courtSurface: 'Superficie',
  courtIndoor: 'Interior / exterior',
  courtLighting: 'Iluminación',
  courtHours: 'Horario operativo',
  courtAdd: 'Agregar cancha',
  courtSchedule: 'Calendario de turnos',
  courtBookShift: 'Reservar turno',
  courtPeakPrice: 'Tarifa pico',
  courtOffPeakPrice: 'Tarifa valle',
  courtMemberPrice: 'Precio socio',
  courtGuestPrice: 'Precio no socio',
  courtRecurringShift: 'Turno fijo semanal',
  courtCancelPolicy: 'Cancelación hasta {hours}h antes',
  courtBookingConfirmed: 'Reserva de cancha confirmada.',
  courtQuoteLoading: 'Calculando precio…',
  courtNoClubs: 'Unite a un club o elegí una institución con canchas para reservar.',
  courtNoSlots: 'No hay turnos libres para esta fecha.',
  courtCancelOk: 'Reserva de cancha cancelada.',
  courtCancelBlocked: 'Ya no se puede cancelar esta reserva (fuera de la política del club).',
  courtPricingTitle: 'Tarifas por franja',
  courtPricingAdd: 'Agregar tarifa',
  courtPricingEmpty: 'Sin tarifas. Agregá al menos una para que los atletas puedan reservar.',
  courtSettingsTitle: 'Política de canchas',
  courtSettingsSaved: 'Configuración de canchas guardada.',
  courtRecurringTitle: 'Turnos fijos',
  courtRecurringCreate: 'Crear turno fijo semanal',
  courtRecurringEmpty: 'Todavía no tenés turnos fijos.',
  courtRecurringCancelled: 'Turno fijo cancelado.',
  courtTypes: {
    padel: 'Pádel',
    tennis: 'Tenis',
    football_5: 'Fútbol 5',
    football_7: 'Fútbol 7',
    football_11: 'Fútbol 11',
    rugby: 'Rugby',
  },
  courtSurfaces: {
    synthetic: 'Sintético',
    grass: 'Césped',
    clay: 'Polvo de ladrillo',
    hard: 'Dura',
    other: 'Otra',
  },
  // Collections F-45
  collectionsTitle: 'Cobros y cuotas',
  collectionsMonthlyRevenue: 'Ingresos del mes (cuotas)',
  collectionsRate: 'Tasa de cobro',
  collectionsUpToDate: 'Socios al día',
  collectionsOverdue: 'Socios morosos',
  collectionsPending: 'Pendientes',
  // Chat V3
  chatTitle: 'Mensajes',
  chatPlaceholder: 'Escribe un mensaje…',
  chatSend: 'Enviar',
  // Open games F-53
  openGamesTitle: 'Partidos abiertos',
  openGamesJoin: 'Unirme',
  openGamesCreate: 'Crear partido',
  openGamesSlots: (filled: number, total: number) => `${filled}/${total} jugadores`,
  // QR F-46
  qrCheckInTitle: 'Control de acceso',
  qrScanHint: 'Escaneá el código QR del socio para validar el ingreso.',
  qrMemberOk: 'Socio al día — acceso permitido',
  qrMemberBlocked: 'Socio con deuda — acceso denegado',
  // Institution search
  searchClubsTab: 'Clubes',
  searchClassesTab: 'Clases',
  // Gym plan V1/V2
  gymBillingSubscribe: 'Activar facturación automática',
  gymBillingActive: 'Facturación automática activa',
  gymBillingDemo: 'Pago simulado del plan SaaS del gimnasio.',
  gymReportsBasicTitle: 'Reportes del club',
  gymReportsAdvancedTitle: 'Reportes avanzados',
  staffSchedulesTitle: 'Horarios del equipo',
  attendanceTitle: 'Control de asistencia',
  attendanceMarkPresent: 'Marcar presente',
  attendanceMarkAbsent: 'Ausente',
  attendanceSaved: 'Asistencia guardada (demostración).',
  brandingTitle: 'Marca del club',
  brandingHint: 'Logo y colores visibles para tus socios en la app.',
  activitiesTitle: 'Actividades y talleres',
  activitiesCreate: 'Nueva actividad',
  enterpriseOnboardingTitle: 'Onboarding dedicado',
  enterpriseIntegrationsTitle: 'Integraciones',
  dedicatedSupportTitle: 'Soporte dedicado',
  prioritySupportBadge: 'Soporte prioritario',
  instructorProSubscribe: 'Suscribirse a Pro',
  instructorProActive: 'Plan Pro activo',
} as const;

export const LIVE_STREAM_LABELS = {
  title: 'Clase en vivo',
  join: 'Unirse a la transmisión',
  joinLiveShort: 'Unirse en vivo',
  leave: 'Salir de la sala',
  endSession: 'Finalizar transmisión',
  connecting: 'Conectando a la sala…',
  reconnecting: 'Reconectando…',
  loginRequired: 'Iniciá sesión para unirte a la transmisión en vivo.',
  notConfigured: 'La transmisión en vivo no está disponible en este momento.',
  bookingRequired: 'Necesitás una reserva confirmada para unirte a esta clase en vivo.',
  outsideWindow:
    'La sala abre 15 minutos antes del inicio y cierra poco después de que termine la clase.',
  sessionEnded: 'Esta transmisión en vivo finalizó.',
  status: {
    scheduled: 'Programada',
    live: 'En vivo',
    ended: 'Finalizada',
    cancelled: 'Cancelada',
  },
  roleHost: 'Anfitrión',
  roleParticipant: 'Participante',
  youAreHost: 'Transmitís como anfitrión de la clase.',
  windowOpen: 'Sala disponible',
  windowClosed: 'Fuera del horario de la sala',
  errorJoin: 'No se pudo unir a la transmisión. Intentá de nuevo.',
  micCameraHint: 'Se solicitará acceso a cámara y micrófono si transmitís.',
} as const;

export const INSTRUCTOR_LABELS = {
  dashboard: {
    hi: 'Hola,',
    todayOverview: 'Resumen del día',
    newClass: 'Nueva clase',
    bookings: 'Reservas',
    revenue: 'Ingresos',
    classes: 'Clases',
    todayClasses: 'Clases de hoy',
  },
  classes: {
    yourClasses: 'Tus clases',
    noClassesYet: 'Aún no tienes clases.',
  },
  calendar: {
    yourCalendar: 'Tu calendario',
    today: 'Hoy',
    month: 'Mes',
    week: 'Semana',
    noEventsDay: 'No hay reservas para este día.',
    moreEvents: (count: number) => `+${count} más`,
    weekdayShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
    weekdayFull: [
      'Domingo',
      'Lunes',
      'Martes',
      'Miércoles',
      'Jueves',
      'Viernes',
      'Sábado',
    ],
  },
  earnings: {
    yourEarnings: 'Tus ingresos',
    totalEarnings: 'Ingresos totales',
    thisMonth: 'Este mes',
    thisWeek: 'Esta semana',
    upcomingPayouts: 'Próximos pagos',
    noEarningsYet: 'Aún no tienes ingresos.',
  },
  notifications: {
    yourNotifications: 'Tus notificaciones',
  },
  publicProfile: {
    instructor: 'Instructor',
    notFound: 'No encontrado.',
    disciplines: 'Área de especialidad',
    expertise: 'Especialidades',
    expertiseEmpty: 'Sin especialidades definidas.',
    bio: 'Presentación',
    bioEmpty: 'Este instructor aún no ha añadido una presentación.',
    certifications: 'Certificaciones',
    certificationsEmpty: 'Sin certificaciones publicadas.',
    from: 'Desde',
    reviews: 'Reseñas',
    reviewsEmpty: 'Aún no hay reseñas de atletas.',
    staffReviews: 'Reseñas del equipo',
    staffReviewsHint: 'Valoraciones de gimnasios donde ha impartido clases.',
    availableNow: 'Disponible ahora',
    notAvailableNow: 'No disponible ahora',
    profileEyebrow: 'Perfil de instructor',
    subtitle: 'Conocé la trayectoria, especialidades y reseñas de este profesional en Fitnexia.',
  },
  classForm: {
    newClass: 'Nueva clase',
    editClass: 'Editar clase',
    className: 'Nombre de la clase',
    description: 'Descripción',
    descriptionPlaceholder: 'Describe la clase, nivel, qué deben traer los participantes…',
    discipline: 'Disciplina',
    modality: 'Modalidad',
    classFormat: 'Tipo de clase',
    level: 'Nivel',
    language: 'Idioma de la clase',
    basicsSection: 'Información básica',
    basicsSectionHint: 'Nombre, disciplina y tipo de sesión.',
    scheduleSection: 'Horario',
    scheduleSectionHint: 'Fecha, hora y duración de la clase.',
    pricingSection: 'Precio y cupos',
    pricingSectionHint: 'Define el costo y cuántas personas pueden reservar.',
    date: 'Fecha (AAAA-MM-DD)',
    time: 'Hora (HH:MM)',
    duration: 'Duración (min)',
    price: 'Precio (UYU)',
    capacity: 'Capacidad',
    cancellationPolicyHours: 'Anticipación para cancelar (horas)',
    cancellationPolicyHint:
      'Los participantes reciben reembolso completo si cancelan con al menos esta cantidad de horas antes de la clase.',
    location: 'Ubicación',
    locationPlaceholder: 'Ej. Av. Italia 1234, Montevideo',
    locationHint: 'Dirección o lugar donde se realiza la clase presencial.',
    locationRequired: 'La ubicación es obligatoria para clases presenciales.',
    publishClass: 'Publicar clase',
    updateClass: 'Actualizar clase',
    classNameRequired: 'El nombre de la clase es obligatorio.',
    classPublished: 'Clase publicada correctamente.',
    classUpdated: 'Clase actualizada correctamente.',
    cancelPanelTitle: 'Cancelar clase',
    cancelPanelHint: 'Esta acción cancela la clase para todos los participantes. No se puede deshacer.',
    cancelConfirmTitle: '¿Cancelar esta clase?',
    cancelConfirmMessage: 'Los participantes serán notificados. Esta acción no se puede deshacer.',
    keepClass: 'Mantener clase',
    classCancelled: 'Clase cancelada correctamente.',
    classCancelFailed: 'No se pudo cancelar la clase',
  },
} as const;

/** F-13 — recurring weekly class series */
export const RECURRENCE_LABELS = {
  sectionTitle: 'Frecuencia',
  recurringToggle: 'Clase recurrente',
  recurringHint:
    'El servidor publica automáticamente las próximas 8 semanas en los días elegidos. Sin fecha de fin hasta que pausés o eliminés la serie.',
  weekdays: 'Días de la semana',
  seriesStart: 'Inicio de la serie',
  weekdaysRequired: 'Seleccioná al menos un día de la semana.',
  previewInstances: 'Próximas sesiones',
  regularBadge: 'Regular',
  regularBadgeTitle: 'Clase regular — forma parte de una serie semanal',
  badge: 'Recurrente',
  badgePaused: 'Serie pausada',
  editScopeTitle: '¿Qué querés modificar?',
  editScopeHint: 'Las instancias pasadas no se modifican.',
  editScopeSingle: 'Solo esta clase',
  editScopeFollowing: 'Esta y todas las siguientes',
  editScheduleSingleHint:
    'La fecha y hora solo se actualizan en «Solo esta clase». En «Esta y las siguientes» se aplican título, precio, capacidad y demás campos.',
  seriesExceptionNotice:
    'Esta sesión fue modificada de forma independiente y ya no sigue el mismo horario que el resto de la serie.',
  seriesDeletedNotice: 'La serie fue eliminada. Esta sesión sigue publicada hasta que la canceles.',
  seriesActionsTitle: 'Serie recurrente',
  pauseSeries: 'Pausar serie',
  pauseSeriesHint: 'Dejás de generar nuevas instancias. Las reservas confirmadas siguen activas.',
  pauseSeriesConfirm: '¿Pausar la serie recurrente?',
  pauseSeriesDone: 'Serie pausada. Las clases ya publicadas siguen visibles.',
  resumeSeries: 'Reanudar serie',
  resumeSeriesDone: 'Serie reactivada.',
  deleteSeries: 'Eliminar serie',
  deleteSeriesHint:
    'Cancela instancias futuras sin reservas. Las que tienen reservas deben cancelarse manualmente.',
  deleteSeriesConfirm: '¿Eliminar la serie recurrente?',
  deleteSeriesDone: 'Serie eliminada.',
  deleteSeriesPartial:
    'Algunas instancias con reservas no se cancelaron automáticamente. Cancelalas una por una.',
  publishSeries: 'Publicar serie',
  publishSeriesDone: (count: number) =>
    `${count} ${count === 1 ? 'sesión publicada' : 'sesiones publicadas'} en el buscador.`,
  weekdayShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'] as const,
} as const;

export const INSTITUTION_PROFILE_LABELS = {
  email: 'Correo electrónico (gimnasio/club)',
  emailHint: 'Este correo es tu acceso al panel y el contacto público del club.',
  phone: 'Teléfono (gimnasio/club)',
  address: 'Dirección (gimnasio/club)',
  city: 'Ciudad (gimnasio/club)',
  country: 'País (gimnasio/club)',
  name: 'Nombre (gimnasio/club)',
  description: 'Descripción (gimnasio/club)',
  website: 'Sitio web (gimnasio/club)',
  openingHours: 'Horario de apertura (club)',
  publicClubLink: 'Ver perfil público del club',
} as const;

export const PUBLIC_CLUB_LABELS = {
  eyebrow: 'Club Fitnexia',
  subtitle: 'Instalaciones, horarios y equipo en un perfil público de tu gimnasio.',
  contact: 'Contacto (gimnasio/club)',
  description: 'Descripción (gimnasio/club)',
  openingHours: 'Horario de apertura (club)',
  team: 'Equipo',
  notAvailable: 'No publicado',
  openToday: 'Ver horario',
} as const;

export const GYM_LABELS = {
  dashboard: {
    controlPanel: 'Panel de control',
    bookingsToday: 'Reservas de hoy',
    revenue: 'Ingresos',
    occupancy: 'Ocupación',
    upcomingClasses: 'Próximas clases',
  },
  classes: {
    yourClasses: 'Tus clases',
    addClass: 'Nueva clase grupal',
    groupOnly: 'Solo clases grupales',
    pickInstructor: 'Instructor asignado',
    assignmentMode: 'Modo de asignación',
    assignmentModeHint: 'Elegí si la clase la organiza el gimnasio (Modelo A) o un instructor de tu equipo (Modelo B).',
    modelA: 'Sin instructor (Modelo A)',
    modelAHint: 'El gimnasio organiza la clase. No se muestra perfil de instructor en el detalle.',
    modelB: 'Con instructor vinculado (Modelo B)',
    modelBHint: 'Asigná un instructor de tu equipo a esta clase grupal.',
    pickInstructorHint: 'Seleccioná un instructor vinculado a tu gimnasio.',
    noInstructorOption: 'Sin instructor asignado (Modelo A)',
    modelBInstructorRequired: 'Seleccioná un instructor vinculado para publicar con Modelo B.',
    gymHostedClass: 'Clase del gimnasio',
    emptyClassesHint: 'Publicá tu primera clase grupal con o sin instructor asignado.',
    editClass: 'Editar clase',
    noLinkedInstructors: 'Aún no tienes instructores vinculados. Agrégalos desde la página de instructores.',
    goToInstructors: 'Ir a instructores',
  },
  instructors: {
    yourInstructors: 'Instructores',
    rosterTitle: 'Directorio de instructores',
    rosterSubtitle: 'Explora perfiles, envía solicitudes de vinculación y valora a tu equipo.',
    addToStaff: 'Agregar',
    pending: 'Pendiente',
    onStaff: 'En equipo',
    review: 'Reseñar',
    reviewSent: 'Reseña enviada',
    reviewLocked: 'Completa una clase con este instructor para reseñar',
    inviteSent: 'Solicitud enviada al instructor',
    alreadyPending: 'Ya hay una solicitud pendiente',
    alreadyLinked: 'Este instructor ya forma parte de tu equipo',
    linkedCount: (n: number) => `${n} en tu equipo`,
    pendingCount: (n: number) => `${n} pendiente${n === 1 ? '' : 's'}`,
    noInstructors: 'No hay instructores registrados en la plataforma.',
    acceptInvite: 'Aceptar invitación',
    inviteFromGym: 'Invitación de gimnasio',
    inviteBody: (gym: string) => `${gym} quiere agregarte a su equipo.`,
    inviteAccepted: 'Te has unido al gimnasio correctamente.',
    removedFromStaff: 'Instructor eliminado del equipo.',
    inviteCancelled: 'Solicitud cancelada.',
    unlinkConfirm: '¿Quitar a este instructor de tu equipo?',
    detail: {
      affiliation: 'Afiliación',
      affiliationLinked: 'Instructor vinculado a tu gimnasio',
      affiliationPending: 'Solicitud de vinculación pendiente',
      affiliationNone: 'Sin vincular — puedes invitarlo desde el directorio',
      disciplines: 'Especialidades',
      athleteReviews: 'Reseñas de atletas',
      staffReviews: 'Evaluaciones de gimnasios',
      yourStaffReview: 'Tu evaluación interna',
      classesAtGym: 'Clases en tu gimnasio',
      noClasses: 'Este instructor no tiene clases publicadas en tu gimnasio.',
      viewInDirectory: 'Volver al directorio',
      notFound: 'Instructor no encontrado.',
    },
  },
  staffReview: {
    title: 'Reseña de instructor',
    subtitle: 'Comparte tu experiencia trabajando con este instructor en tu gimnasio.',
    ratingLabel: 'Calificación',
    commentLabel: 'Comentario',
    commentPlaceholder: 'Describe puntualidad, trato con alumnos, preparación de la clase…',
    submit: 'Publicar reseña',
    notEligible: 'Aún no puedes reseñar a este instructor.',
    needCompletedClass: 'Debe haber completado al menos una clase en tu gimnasio.',
    needLinked: 'El instructor debe estar vinculado a tu gimnasio.',
    alreadyReviewed: 'Ya publicaste una reseña para este instructor.',
    success: 'Reseña publicada correctamente.',
  },
  earnings: {
    yourEarnings: 'Ingresos del gimnasio',
  },
  plan: {
    yourPlan: 'Tu plan',
    planTitle: 'Plan Fitnexia',
    planDescription:
      'Tu suscripción Fitnexia define el límite de socios activos y las funciones incluidas. Las cuotas que cobrás a tus socios se configuran aparte.',
    loadError: 'No se pudieron cargar los planes.',
  },
  saas: {
    currentPlan: 'Plan Fitnexia',
    currentBadge: 'Plan actual',
    memberUsage: 'Socios activos',
    billingManual: 'Facturación manual (contacto comercial)',
    atLimit: 'Límite alcanzado',
    remaining: (n: number) => `${n} cupos disponibles`,
    selectPlan: 'Seleccionar plan',
    tierUpdated: 'Plan actualizado correctamente.',
    billingActive: 'Débito automático activo',
    billingPending: 'Pago pendiente de autorización',
    billingPastDue: 'Pago atrasado',
    billingNotRequired: 'Sin costo mensual',
    billingInactive: 'Facturación inactiva',
    nextBilling: 'Próximo cobro',
    pendingTierTitle: 'Cambio de plan pendiente',
    pendingTierBody: (tierName: string) =>
      `Autorizá el débito automático en Mercado Pago para activar el plan ${tierName}.`,
    completePayment: 'Completar pago en Mercado Pago',
    refreshBilling: 'Ya pagué, actualizar estado',
    checkoutOpenedTitle: 'Autorización en Mercado Pago',
    checkoutOpenedBody:
      'Abrimos Mercado Pago en una pestaña nueva. Cuando completes la autorización, el plan se activa automáticamente.',
    tierActivated: 'Plan activado correctamente.',
    activationTimeout:
      'Todavía no recibimos la confirmación del pago. Si ya pagaste, actualizá esta página en unos minutos.',
    memberLimitReached: (limit: number) =>
      `Alcanzaste el límite de ${limit} socios activos de tu plan. Actualizá tu plan Fitnexia o dá de baja socios para agregar más.`,
    limitBlocked: 'No podés agregar más socios hasta liberar cupo o cambiar de plan.',
  },
  jobs: {
    title: 'Ofertas de empleo',
    subtitle: 'Publicá vacantes para instructores, entrenadores y staff.',
    create: 'Nueva oferta',
    empty: 'No hay ofertas publicadas.',
    applications: 'Postulaciones',
    apply: 'Postularme',
    applied: 'Ya postulaste a esta oferta.',
    applySuccess: 'Postulación enviada correctamente.',
    saved: 'Oferta guardada.',
    deleted: 'Oferta eliminada.',
    browseTitle: 'Empleos en gimnasios',
    browseSubtitle: 'Encontrá oportunidades en clubs de Fitnexia.',
    searchPlaceholder: 'Yoga, funcional, Pilates…',
    myApplications: 'Mis postulaciones',
    noApplications: 'Aún no postulaste a ninguna oferta.',
    fields: {
      title: 'Título',
      roleType: 'Tipo de rol',
      description: 'Descripción',
      disciplines: 'Disciplinas (separadas por coma)',
      status: 'Estado',
      expiresAt: 'Vence (opcional)',
    },
  },
} as const;

export const INSTRUCTOR_JOB_LABELS = {
  planDescription:
    'Compara comisiones de marketplace según tu plan de instructor. Los cobros de clases usan Mercado Pago cuando el marketplace está activo.',
} as const;

export const CLUB_LABELS = {
  feeStatus: {
    current: 'Al día',
    pending: 'Pendiente',
    overdue: 'Moroso',
  },
  planCadence: {
    monthly: 'Mensual',
    quarterly: 'Trimestral',
    annual: 'Anual',
  },
  plans: {
    title: 'Planes de membresía del club',
    subtitle: 'Definí las cuotas que cobrarás a tus socios. Son independientes del plan Fitnexia.',
    create: 'Nuevo plan',
    edit: 'Editar plan',
    name: 'Nombre del plan',
    cadence: 'Frecuencia',
    price: 'Precio (UYU)',
    familySlots: 'Cupos familiares (opcional)',
    active: 'Plan activo',
    empty: 'Aún no hay planes de membresía. Creá el primero para dar de alta socios.',
    saved: 'Plan guardado correctamente.',
    deactivated: 'Plan desactivado.',
    fitnexiaPlanHint: 'Para comisiones de la plataforma, visitá Plan y comisión en tu perfil.',
    settingsTitle: 'Configuración de cobros',
    settingsSubtitle: 'Recordatorios y período de gracia antes de marcar morosidad.',
    reminderDays: 'Días antes del vencimiento para recordatorio',
    graceDays: 'Días de gracia antes de marcar moroso',
    saveSettings: 'Guardar configuración',
  },
  members: {
    title: 'Socios del club',
    subtitle: 'Gestioná altas, bajas y el estado de cuota de cada socio.',
    add: 'Agregar socio',
    invite: 'Invitar socios',
    import: 'Importar CSV',
    searchPlaceholder: 'Buscar por nombre o email…',
    filterAll: 'Todos',
    empty: 'No hay socios registrados.',
    loadError: 'No se pudieron cargar los socios. El servicio puede no estar disponible todavía.',
    billingNote:
      'Con cobros manuales, registrá cada pago desde el detalle del socio. Los recordatorios automáticos se envían antes del vencimiento.',
    markPaid: 'Marcar como pagado',
    markPending: 'Marcar como pendiente',
    markPaidSuccess: 'Pago registrado. El socio quedó al día.',
    markPendingSuccess: 'Cuota marcada como pendiente.',
    deactivateConfirm: '¿Dar de baja a este socio?',
    deactivated: 'Socio dado de baja.',
    saved: 'Socio guardado.',
    edit: 'Editar socio',
    editSaved: 'Datos del socio actualizados.',
    filterPlan: 'Filtrar por plan',
    allPlans: 'Todos los planes',
    previousPage: 'Anterior',
    nextPage: 'Siguiente',
    pageOf: (page: number, totalPages: number) => `Página ${page} de ${totalPages}`,
    phone: 'Teléfono',
    columns: {
      name: 'Nombre',
      email: 'Email',
      plan: 'Plan',
      status: 'Estado de cuota',
      nextDue: 'Próximo vencimiento',
    },
    summary: {
      overdue: 'Socios morosos',
      current: 'Al día',
      pending: 'Pendientes',
      collectionRate: 'Tasa de cobro',
    },
  },
  invites: {
    title: 'Invitaciones de socios',
    subtitle: 'Enviá invitaciones por email, link o carga masiva CSV.',
    email: 'Email del socio',
    plan: 'Plan de membresía',
    message: 'Mensaje (opcional)',
    send: 'Enviar invitación',
    linkTitle: 'Link de invitación',
    copyLink: 'Copiar link',
    copied: 'Link copiado.',
    csvTitle: 'Importación masiva',
    csvHint: 'Columnas: email, firstName, lastName, phone (opcional), planId',
    upload: 'Subir CSV',
    importResult: (ok: number, fail: number) =>
      `Importados: ${ok}. Errores: ${fail}.`,
    sent: 'Invitación enviada.',
    pending: 'Invitaciones pendientes',
    loadError: 'No se pudieron cargar las invitaciones.',
    cancel: 'Cancelar',
    cancelled: 'Invitación cancelada.',
    createLink: 'Generar link de invitación',
    linkCreated: 'Link de invitación creado.',
  },
  billing: {
    subscribe: 'Activar débito automático',
    retry: 'Reintentar cobro',
    subscribeHint: 'Autorizá el débito recurrente en Mercado Pago desde tu estado de cuenta.',
    authorize: 'Autorizar débito automático',
    subscriptionActive: 'Suscripción activa',
    subscriptionPastDue: 'Pago atrasado',
    charges: 'Historial de cargos',
    noCharges: 'Sin cargos registrados.',
    paymentOpenedTitle: 'Pago en Mercado Pago',
    paymentOpenedBody:
      'Abrimos Mercado Pago en una pestaña nueva. Cuando completes el pago, tu estado de cuenta se actualiza automáticamente.',
    waitingPayment: 'Esperando confirmación del pago…',
    paymentApproved: 'Pago acreditado. ¡Gracias!',
    paymentTimeout:
      'Todavía no recibimos la confirmación. Si ya pagaste, actualizá el estado de cuenta en unos minutos.',
    payError: 'No se pudo iniciar el pago.',
  },
  join: {
    title: 'Unite al club',
    invalid: 'Esta invitación no es válida o expiró.',
    accept: 'Aceptar invitación',
    loginRequired: 'Iniciá sesión o creá una cuenta para continuar.',
    success: '¡Bienvenido al club!',
    redirectPay: 'Completá la autorización de pago en Mercado Pago.',
  },
  athlete: {
    title: 'Membresías de club',
    subtitle: 'Cuotas y estado de cuenta en los clubes donde sos socio.',
    empty: 'No pertenecés a ningún club todavía.',
    statement: 'Estado de cuenta',
    balanceDue: 'Saldo adeudado',
    nextDue: 'Próximo vencimiento',
    payNow: 'Pagar ahora',
    chargeHistory: 'Historial de cuotas',
    noCharges: 'Sin movimientos.',
  },
} as const;

export const MOBILE_APP_LABELS = {
  title: 'Descarga la app',
  subtitle: 'Reservá y entrená desde tu celular.',
  heroCta: 'Descargar la app',
  heroHint: 'Disponible en iOS y Android',
  openStores: 'Ver tiendas',
  ios: 'App Store',
  android: 'Google Play',
  androidApk: 'Descargar APK',
  iosMicro: 'Download on the',
  androidMicro: 'Get it on',
  androidApkMicro: 'Android',
  iosAria: 'Descargar Fitnexia en la App Store',
  androidAria: 'Descargar Fitnexia en Google Play',
  androidApkAria: 'Descargar Fitnexia APK para Android',
  comingSoon: 'Próximamente',
  comingSoonAria: 'Disponible próximamente',
  modalTitle: 'Llevá Fitnexia en el bolsillo',
  modalSubtitle: 'Descargá la app para reservar clases, recibir recordatorios y entrenar donde estés.',
  modalClose: 'Cerrar',
  bannerTitle: 'Fitnexia App',
  bannerSubtitle: 'Reservas, recordatorios y tu progreso en el celular.',
  bannerCta: 'Abrir',
  bannerDismiss: 'Cerrar aviso de la app',
  authPromoTitle: '¿Preferís la app?',
  authPromoBody: 'Más rápida en el celular — disponible en App Store y Android.',
  authPromoCta: 'Descargar app',
  navDownload: 'App',
} as const;
